cloud:
  aws:
    credentials:
      access-key:
      secret-key:
    region:
      static: eu-west-1
    stack:
      auto: false

application:
  bucket:
    name: ecommerce-service-file


logging:
  level:
    org:
      springframework:
        security: DEBUG

jwt:
  auth:
    converter:
      resource-id: ecommerce-service-client
      principle-attribute: principal_username

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/master
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

  mail:
    host: smtp.gmail.com
    port: 465
    username: rachidbenkitou2021@gmail.com
    password: kxmd uimm jntc qxqq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    url: jdbc:mysql://localhost/ecommerce_service?createDatabaseIfNotExist=true
    username: root
    password:
#    password: your_mysql_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  servlet:
    context-path: /api
  port: 9090


# My Custom Params
myKeycloak:
  users-endpoint: http://localhost:8080/admin/realms/master/users
  token-endpoint: http://localhost:8080/realms/master/protocol/openid-connect/token
  logout-endpoint: http://localhost:8080/realms/master/protocol/openid-connect/logout
  roles-endpoint: http://localhost:8080/admin/realms/master/roles
  introspect-endpoint: http://localhost:8080/realms/master/protocol/openid-connect/token/introspect
  client-id: admin-cli
  realm: master
  client-secret: FJRMxrU81GGOhA4KlPHPLbOcSbbSaxPD


  client:
    default-role-id: 2a0e9424-ed1b-4ec6-8138-daec9c1e9735
    default-role-name: client


