cloud:
  aws:
    credentials:
      access-key: AKIA2YQZPC7UBEEZKPAX
      secret-key: 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
    region:
      static: eu-west-1
    stack:
      auto: false

application:
  bucket:
    name: ecommerce-file
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    url: jdbc:mysql://localhost/ecommerce?createDatabaseIfNotExist=true
    username: root
    password:
    #url: jdbc:mysql://ecommerce.cvgjytfrsxst.eu-west-1.rds.amazonaws.com:3306/ecommerce?createDatabaseIfNotExist=true
    #username: ecommerce
    #password: ecommerce
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  servlet:
    context-path: /api
  port: 9090
